In [16]:
#dataset
import numpy as np
X=np.array(([2,9],[1,5],[3,6]), dtype=float)
Y=np.array(([92],[86],[89]),dtype=float)
X=X/np.amax(X,axis=0)   # take the max for each col, normalize
actual_op=Y/100
print(X)
print(actual_op)

[[0.66666667 1.        ]
 [0.33333333 0.55555556]
 [1.         0.66666667]]
[[0.92]
 [0.86]
 [0.89]]


In [17]:
#activation functions
def sigmoid(x):
    return 1/(1+np.exp(-x))
def derivative_sigmoid(x):
    return x*(1-x)

In [18]:
#feed forward network
#np.random.seed(1)
epoch=1000
lr=0.15
ip_neuron=2; hidden_neuron=3; op_neuron=1
wh=np.random.uniform(low=-0.05,high=0.05,
                    size=(ip_neuron,hidden_neuron)) #2X3
#print(wh)
bh=np.random.uniform(low=-0.05,high=0.05,
                    size=(1,hidden_neuron))
wo=np.random.uniform(low=-0.05,high=0.05,
                    size=(hidden_neuron,op_neuron))   #3X1
bo=np.random.uniform(low=-0.05,high=0.05,
                    size=(1,op_neuron))

print(f'wh{wh} \n bh{bh} \n wo{wo} \n bo{bo}')


wh[[-0.04849936  0.03183416  0.03919709]
 [ 0.04779636  0.0176853   0.0417171 ]] 
 bh[[-0.03192838  0.03326704 -0.04363637]] 
 wo[[-0.04239626]
 [-0.04496682]
 [-0.03848696]] 
 bo[[-0.03050403]]


In [19]:
#train the ANN using backpropagation

for i in range(epoch):
    net_h=np.dot(X,wh)+bh
    sigma_h=sigmoid(net_h)
    
    net_o=np.dot(sigma_h,wo)+bo
    output=sigmoid(net_o)
    
    eo=actual_op-output
    outgrad=derivative_sigmoid(output)
    d_output=eo*outgrad    #err =oj(1-oj)(tj-oj)
    
    eh=d_output.dot(wo.T)
    hiddengrad=derivative_sigmoid(sigma_h)
    d_hidden=eh*hiddengrad
    
    wo+=sigma_h.T.dot(d_output)*lr
    wh+=X.T.dot(d_hidden)*lr
    
    sum_error=0
    for j in range(len(actual_op)):
        print(output[j],actual_op[j])
        sum_error+=((output[j]-actual_op[j])**2)
    
    sum_error/=2
    print(f'Epoch {i} error {sum_error}')
    



[0.47644283] [0.92]
[0.47658385] [0.86]
[0.47651648] [0.89]
Epoch 0 error [0.25735977]
[0.48533189] [0.92]
[0.48539112] [0.86]
[0.48536559] [0.89]
Epoch 1 error [0.2464986]
[0.49404472] [0.92]
[0.49402581] [0.86]
[0.49403928] [0.89]
Epoch 2 error [0.23607995]
[0.50257899] [0.92]
[0.50248379] [0.86]
[0.50253522] [0.89]
Epoch 3 error [0.22609355]
[0.51093312] [0.92]
[0.51076184] [0.86]
[0.51085179] [0.89]
Epoch 4 error [0.21652818]
[0.51910618] [0.92]
[0.51885765] [0.86]
[0.51898808] [0.89]
Epoch 5 error [0.2073719]
[0.52709788] [0.92]
[0.52676972] [0.86]
[0.52694376] [0.89]
Epoch 6 error [0.19861216]
[0.53490845] [0.92]
[0.53449726] [0.86]
[0.53471905] [0.89]
Epoch 7 error [0.19023604]
[0.5425386] [0.92]
[0.54204017] [0.86]
[0.54231467] [0.89]
Epoch 8 error [0.18223032]
[0.54998949] [0.92]
[0.54939895] [0.86]
[0.54973174] [0.89]
Epoch 9 error [0.17458164]
[0.55726264] [0.92]
[0.55657461] [0.86]
[0.55697179] [0.89]
Epoch 10 error [0.16727658]
[0.56435991] [0.92]
[0.56356867] [0.86]
[0.56

[0.87373052] [0.92]
[0.85687072] [0.86]
[0.87214385] [0.89]
Epoch 245 error [0.00123475]
[0.87389632] [0.92]
[0.85702607] [0.86]
[0.87230923] [0.89]
Epoch 246 error [0.00122368]
[0.87406065] [0.92]
[0.85718006] [0.86]
[0.87247315] [0.89]
Epoch 247 error [0.00121278]
[0.87422353] [0.92]
[0.8573327] [0.86]
[0.87263562] [0.89]
Epoch 248 error [0.00120206]
[0.87438499] [0.92]
[0.85748401] [0.86]
[0.87279667] [0.89]
Epoch 249 error [0.00119151]
[0.87454503] [0.92]
[0.857634] [0.86]
[0.8729563] [0.89]
Epoch 250 error [0.00118112]
[0.87470368] [0.92]
[0.85778268] [0.86]
[0.87311454] [0.89]
Epoch 251 error [0.0011709]
[0.87486094] [0.92]
[0.85793008] [0.86]
[0.8732714] [0.89]
Epoch 252 error [0.00116083]
[0.87501684] [0.92]
[0.85807621] [0.86]
[0.8734269] [0.89]
Epoch 253 error [0.00115093]
[0.87517139] [0.92]
[0.85822107] [0.86]
[0.87358105] [0.89]
Epoch 254 error [0.00114118]
[0.87532461] [0.92]
[0.85836469] [0.86]
[0.87373386] [0.89]
Epoch 255 error [0.00113158]
[0.8754765] [0.92]
[0.858507

[0.89439717] [0.92]
[0.87613793] [0.86]
[0.89267432] [0.89]
Epoch 604 error [0.00046154]
[0.89441187] [0.92]
[0.87615095] [0.86]
[0.89268861] [0.89]
Epoch 605 error [0.00046142]
[0.89442648] [0.92]
[0.8761639] [0.86]
[0.89270282] [0.89]
Epoch 606 error [0.00046129]
[0.89444101] [0.92]
[0.87617677] [0.86]
[0.89271694] [0.89]
Epoch 607 error [0.00046117]
[0.89445546] [0.92]
[0.87618956] [0.86]
[0.89273098] [0.89]
Epoch 608 error [0.00046104]
[0.89446983] [0.92]
[0.87620226] [0.86]
[0.89274494] [0.89]
Epoch 609 error [0.00046092]
[0.89448411] [0.92]
[0.8762149] [0.86]
[0.89275882] [0.89]
Epoch 610 error [0.0004608]
[0.89449831] [0.92]
[0.87622745] [0.86]
[0.89277261] [0.89]
Epoch 611 error [0.00046068]
[0.89451243] [0.92]
[0.87623992] [0.86]
[0.89278633] [0.89]
Epoch 612 error [0.00046056]
[0.89452648] [0.92]
[0.87625232] [0.86]
[0.89279996] [0.89]
Epoch 613 error [0.00046044]
[0.89454044] [0.92]
[0.87626465] [0.86]
[0.89281352] [0.89]
Epoch 614 error [0.00046032]
[0.89455432] [0.92]
[0.8

[0.89659945] [0.92]
[0.87791821] [0.86]
[0.89474585] [0.89]
Epoch 915 error [0.00044559]
[0.8966023] [0.92]
[0.87791988] [0.86]
[0.89474827] [0.89]
Epoch 916 error [0.00044556]
[0.89660514] [0.92]
[0.87792154] [0.86]
[0.89475068] [0.89]
Epoch 917 error [0.00044554]
[0.89660797] [0.92]
[0.87792318] [0.86]
[0.89475308] [0.89]
Epoch 918 error [0.00044551]
[0.89661078] [0.92]
[0.87792481] [0.86]
[0.89475547] [0.89]
Epoch 919 error [0.00044548]
[0.89661358] [0.92]
[0.87792643] [0.86]
[0.89475784] [0.89]
Epoch 920 error [0.00044546]
[0.89661636] [0.92]
[0.87792803] [0.86]
[0.8947602] [0.89]
Epoch 921 error [0.00044543]
[0.89661914] [0.92]
[0.87792963] [0.86]
[0.89476255] [0.89]
Epoch 922 error [0.00044541]
[0.8966219] [0.92]
[0.87793121] [0.86]
[0.89476488] [0.89]
Epoch 923 error [0.00044538]
[0.89662465] [0.92]
[0.87793277] [0.86]
[0.8947672] [0.89]
Epoch 924 error [0.00044536]
[0.89662738] [0.92]
[0.87793433] [0.86]
[0.89476951] [0.89]
Epoch 925 error [0.00044533]
[0.8966301] [0.92]
[0.877

In [20]:
print("Normalized Input: \n" + str(X))
print("Actual Output: \n" + str(actual_op))
print("Predicted Output: \n" ,output)

Normalized Input: 
[[0.66666667 1.        ]
 [0.33333333 0.55555556]
 [1.         0.66666667]]
Actual Output: 
[[0.92]
 [0.86]
 [0.89]]
Predicted Output: 
 [[0.89679849]
 [0.87801955]
 [0.89490898]]
